### PR TITLE
Add some footprints and RGB LEDs

### PR DESCRIPTION
**Pull request by carbncl**
USBA / Kailh Choc / ATMEGA32U4-AU / SK8612-MINI-E

### CODE REVIEW

**Comment by carbncl** [comment]
Amended with feedbacks from #2

**Comment by joshajohnson** [comment]
Schematic is looking great, nice work!

**Comment by vguerci** [comment]
Thanks, feel free to merge ;) not sure how you want to work on this git wise

**Comment by carbncl** [comment]
Thanks, feel free to merge ;) not sure how you want to work on this git wise

**Comment by joshajohnson** [comment]
I have no idea what the usual process is, so feel free to do whatever works best

**Pull request merged**
